# SITE CONFIGURATION
baseurl: ""
url: "https://leanwork.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: LeanWork Dev Blog
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "Desenvolvimento, web, mobile, UX e Scrum - Aprenda com os desenvolvedores da LeanWork" # used by search engines

  # Header and footer text
  header_text: >
     <p>Falamos sobre tecnologia, desenvolvimento web, mobile, UX e Scrum</p>

     <p>Aprenda com os desenvolvedores da LeanWork</p>
  header_text_feature_image:
  footer_text: >
   2018 - Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>

  # Icons
  rss: false
  email_address: "contato@leanwork.com.br" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "leanwork"
  flickr:
  gitlab:
  github: "leanwork"
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/company/leanwork-tecnologia/" # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: 
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "Comentar"
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Siga-nos"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Proxímo Post"
  str_previous_post: "Post Anterior"
  str_next_page: "Próximos"
  str_previous_page: "Anteriores"
  str_continue_reading: "Continuar lendo"
  str_javascript_required_disqus: "Por favor habilite o JavaScript do seu navegador para ver os comentários."
  str_search_no_results: "Não encontramos o que voce procurava :("

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
